### ISSUE TITLE
Problem with Strings and some general questions

### ISSUE THREAD

**Issue by ghost** [ScalABLE40/robin#2] opened 2020-03-12 12:51 UTC
Hello,

I am currently trying out this project with ubuntu 16.04 and ros kinetic. And I really like it so far, but while using I ran into some things I could not explain myself. By opening this issue I hope to find some answers:

1. I was able to transfer numbers between codesys and ros by adding RobinSubscribers and Publishers to the robin_node.cpp. What I could not get to work is sending strings in either direction. While sending a String from ROS to Codesys the orignial strings gets altered: e.g. from "Hello" to something like "pF$02". After that the value can not be changed until a complete reset of the PLC. Sending a string from codesys to ros results in sending no string at all (no information published on topic). Did I forgot something or did I made a mistake?

Here is an excerpt of the lines I added:
robin_inst.cpp:
```
#include "robin_publisher.cpp"
#include "robin_subscriber.cpp"
#include "robin/structs.h"
#include "std_msgs/Int32.h"
#include "std_msgs/String.h"

template class RobinSubscriber<int32_t, std_msgs::Int32>;
template class RobinSubscriber<std::string, std_msgs::String>;
template class RobinPublisher<std::string, std_msgs::String>;
template class RobinPublisher<int32_t, std_msgs::Int32>;
```

robin_node.cpp
```
//works
RobinSubscriber<int32_t, std_msgs::Int32> pub_int32(nh, "pub_int32");
RobinPublisher<int32_t, std_msgs::Int32> sub_int32(nh, "sub_int32");

// does not work
RobinSubscriber<std::string, std_msgs::String> pub_string(nh, "pub_string");
RobinPublisher<std::string, std_msgs::String> sub_string(nh, "sub_string");
```

codesys
```
VAR_INPUT
 	sub_int32 : DINT;
	sub_string : STRING;
END_VAR
 
VAR_OUTPUT
	pub_int32 : DINT;
 	pub_string : STRING;
END_VAR
 
robin();
robin.write('sub_int32', sub_int32);
robin.write('sub_string', sub_string);
robin.read('pub_int32', pub_int32);
robin.read('pub_string', pub_string);
```

2. I noticed that variables regardless of whether the content has changed or not gets published. On PLC-side this does not bother me, but in my opinion this is some what a problem on ROS-side. My problem with this behavior is, that for ROS every published message is a new information and triggers the callback functions of the subscrubers. In some of my usecases I need to intercept this by doing something like: "if old information == new information do nothing".
The question I now ask myself is whether this behaviour is intended or not and if there is a possibility to do a interception of this behavior on plc-side or the code itself?

Beside that I would really appreciate if you could add/bring back an example for custom messages and and structs. Moreover I could not load the provided PLCopenXML because of an "Device not found" - Error. I tried to install some packages, but that did not solved the problem. Since the provided picture contains all information of the XML I could work around that.

Thanks in advance for any help you are able to provide.

hrdb

**Comment by henriquedomingos** [comment] 2020-03-17 12:24
Hello,

We are happy to hear that you are enjoying our _ROS-CODESYS Bridge_ and we are available to clarify your doubts and help you to understand our system better.

In our development scenario, we used _Ubuntu 16.04_ and _ROS Kinetic_ but now we have migrated to _Ubuntu 18.04_ and _ROS Melodic_ so your setup shouldn't be a problem.
Relatively to _CODESYS_, we are using the _Version 3.5 SP15_ and the _CODESYS Control for Linux SL_ (3.15).

So, let's address each question of the issue:

1. Problems sending strings in both directions

	You are using the _master_ branch, right? I believe that was a problem not yet solved in that branch. 
	It was however addressed in the _develop_ branch. I am gonna ask you to try it and see if no problems occur.
	
	In the _develop_ branch, things are quite different. There is no need to write the C++ code in the ROS side, you only need to specify the variables you want to pass.
	Then you run a python script via _CODESYS_ that will generate and compile all the necessary code. Everything is explained in the README but if you have any problems just ask. 


2. Variables published whether the content has changed or not

	This was indeed an intended behavior. Nonetheless, we will take your opinion into account and discuss it. Perhaps include it as a feature in the future.


3. Examples for Custom messages

	I have created a new example available through the XML file (codesys_project.xml). In case you are not able to open it, I also placed some pictures with the project example.


4. Error importing _PLCOpenXML_ due to "Device not found" Error.

	Not sure what is causing this error. Perhaps a problem with the CODESYS versions, make sure you are using the 3.15 version of the _CODESYS Control for Linux SL_.


Thanks for the feedback,
Henrique

**Comment by ghost** [comment] 2020-03-19 08:13
Hello Henrique,

you were right I used the master branch. After switching to the develop branch everything is working fine. I needed a bit time to get my head through the changed usage in the dev branch, but using the scripts is really convenient. 

Reflecting your hint in point 4 I looked into the provided .xml-Files and found the device setting. I edited that setting according to my version (control for linux sl 3.5.15.30) and was able to import the files. This might not be the cleanest way to solve this, but it worked for me. 

[https://github.com/ScalABLE40/robin/blob/master/src/codesys/example_project.xml](url)
[https://github.com/ScalABLE40/robin/blob/develop/robin_updater/cfg/codesys_project.xml](url)

`<Version>3.5.15.0</Version>` to `<Version>3.5.15.30</Version>`

```
<data name="Device" handleUnknown="discard">
  <Device xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="">
    <DeviceType>
      <DeviceIdentification>
        <Type>4102</Type>
        <Id>0000 0005</Id>
        <Version>3.5.15.0</Version>
      </DeviceIdentification>
      <Connector moduleType="256" interface="Common.PCI" connectorId="0">
        <HostParameterSet />
      </Connector>
      <Connector moduleType="1279" interface="Common.SoftMotion.General" connectorId="1">
        <HostParameterSet />
      </Connector>
      <DeviceParameterSet />
    </DeviceType>
  </Device>
</data>
```

For my part I consider this issue closed. Thank you for your help,
hrdb

**Closed as completed** 2020-03-20 17:43 UTC
